[project]
name = "chat-evals"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=3.20.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
chat-evals = "chat_evals:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
